DROP TABLE places CASCADE;
DROP TABLE characters CASCADE;
DROP TABLE animals CASCADE;
DROP TABLE action_logs CASCADE;
DROP TABLE sound_logs CASCADE;
DROP TABLE states CASCADE;
DROP TABLE objects CASCADE;
DROP TABLE objects_in_actions CASCADE;

DROP TYPE GENDERS;